-- 主动健康干预闭环 — 已有库增量迁移（MySQL 8.0）
-- 全新部署请直接使用 db/init.sql

USE DIABETES_USER;

CREATE TABLE IF NOT EXISTS HEALTH_INTERVENTION_LOGS (
    PLAN_ID        VARCHAR(32)   NOT NULL PRIMARY KEY COMMENT '干预计划ID ivp_',
    USER_ID        VARCHAR(32)   NOT NULL COMMENT '用户ID',
    TRIGGER_TYPE   VARCHAR(32)   NOT NULL COMMENT 'health_record_saved/checkin_created/...',
    SEVERITY       VARCHAR(16)   NOT NULL COMMENT 'info/warning/critical',
    RISK_LEVEL     VARCHAR(16)   DEFAULT NULL COMMENT 'normal/attention/warning/critical',
    SUMMARY        VARCHAR(500)  NOT NULL COMMENT '干预摘要',
    EVIDENCE       JSON          DEFAULT NULL COMMENT 'evidence 数组',
    ACTIONS        JSON          NOT NULL COMMENT 'actions 数组',
    MESSAGE_ID     VARCHAR(32)   DEFAULT NULL COMMENT '关联 USER_MESSAGES',
    STATUS         VARCHAR(16)   NOT NULL DEFAULT 'active' COMMENT 'active/resolved/expired',
    EXPIRES_AT     DATETIME      DEFAULT NULL COMMENT '干预过期时间',
    RESOLVED_AT    DATETIME      DEFAULT NULL COMMENT '指标改善后关闭时间',
    CREATED_AT     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    INDEX IDX_USER_STATUS (USER_ID, STATUS, CREATED_AT DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='主动健康干预日志';

USE DIABETES_CHECKIN;

-- 若列已存在，执行时会报错，可跳过对应语句
ALTER TABLE CHECKIN_REMINDER_RULES
    ADD COLUMN RULE_SOURCE VARCHAR(16) NOT NULL DEFAULT 'user'
        COMMENT 'user=用户配置 system=系统干预' AFTER ENABLED;

ALTER TABLE CHECKIN_REMINDER_RULES
    ADD COLUMN INTERVENTION_ID VARCHAR(32) DEFAULT NULL
        COMMENT '关联 HEALTH_INTERVENTION_LOGS.PLAN_ID' AFTER RULE_SOURCE;

ALTER TABLE CHECKIN_REMINDER_RULES
    ADD COLUMN EXPIRES_AT DATETIME DEFAULT NULL
        COMMENT '系统规则过期时间 NULL=永久' AFTER INTERVENTION_ID;

CREATE INDEX IDX_USER_SOURCE ON CHECKIN_REMINDER_RULES (USER_ID, RULE_SOURCE, EXPIRES_AT);
