import { afterEach, describe, expect, it, vi } from 'vitest'

describe('config', () => {
  afterEach(() => {
    vi.unstubAllEnvs()
    vi.resetModules()
  })

  it('uses defaults when env vars are empty', async () => {
    vi.stubEnv('VITE_USE_MOCK', '')
    vi.stubEnv('VITE_API_BASE', '')
    vi.stubEnv('VITE_API_V2_BASE', '')
    vi.stubEnv('VITE_ADMIN_PORTAL_URL', '')
    vi.stubEnv('VITE_DIFY_QA_URL', '')
    vi.stubEnv('VITE_DIFY_CONSULTATION_URL', '')
    vi.stubEnv('VITE_DIFY_RISK_URL', '')
    vi.stubEnv('VITE_DIFY_PLAN_URL', '')
    vi.stubEnv('VITE_DIFY_ARTICLE_DRAFT_URL', '')
    const config = await import('../index.js')
    expect(config.USE_MOCK).toBe(true)
    expect(config.API_BASE).toBe('/api/v1')
    expect(config.API_V2_BASE).toBe('/api/v2')
    expect(config.ADMIN_PORTAL_URL).toBe('http://localhost:5174')
    expect(config.DIFY_WORKFLOWS.QA).toBe('__PLACEHOLDER_DIFY_QA_WORKFLOW__')
    expect(config.DIFY_WORKFLOWS.CONSULTATION).toBe('__PLACEHOLDER_DIFY_CONSULTATION_WORKFLOW__')
    expect(config.DIFY_WORKFLOWS.RISK).toBe('__PLACEHOLDER_DIFY_RISK_WORKFLOW__')
    expect(config.DIFY_WORKFLOWS.PLAN).toBe('__PLACEHOLDER_DIFY_PLAN_WORKFLOW__')
    expect(config.DIFY_WORKFLOWS.ARTICLE_DRAFT).toBe('__PLACEHOLDER_DIFY_ARTICLE_DRAFT_WORKFLOW__')
  })

  it('reads custom env values', async () => {
    vi.stubEnv('VITE_USE_MOCK', 'false')
    vi.stubEnv('VITE_API_BASE', '/custom/v1')
    vi.stubEnv('VITE_API_V2_BASE', '/custom/v2')
    vi.stubEnv('VITE_ADMIN_PORTAL_URL', 'http://admin.test')
    vi.stubEnv('VITE_DIFY_QA_URL', 'http://dify.test/qa')
    vi.stubEnv('VITE_DIFY_CONSULTATION_URL', 'http://dify.test/consult')
    vi.stubEnv('VITE_DIFY_RISK_URL', 'http://dify.test/risk')
    vi.stubEnv('VITE_DIFY_PLAN_URL', 'http://dify.test/plan')
    vi.stubEnv('VITE_DIFY_ARTICLE_DRAFT_URL', 'http://dify.test/article')
    const config = await import('../index.js')
    expect(config.USE_MOCK).toBe(false)
    expect(config.API_BASE).toBe('/custom/v1')
    expect(config.API_V2_BASE).toBe('/custom/v2')
    expect(config.ADMIN_PORTAL_URL).toBe('http://admin.test')
    expect(config.DIFY_WORKFLOWS.QA).toBe('http://dify.test/qa')
    expect(config.DIFY_WORKFLOWS.CONSULTATION).toBe('http://dify.test/consult')
    expect(config.DIFY_WORKFLOWS.RISK).toBe('http://dify.test/risk')
    expect(config.DIFY_WORKFLOWS.PLAN).toBe('http://dify.test/plan')
    expect(config.DIFY_WORKFLOWS.ARTICLE_DRAFT).toBe('http://dify.test/article')
  })
})
