-- =============================================================================
-- 糖尿病智能助手 - 分库初始化脚本
-- 字符集：utf8mb4 | 表名/字段名：大写
-- =============================================================================
-- 分库说明：
--   DIABETES_USER         用户与管理员
--   DIABETES_DOCTOR       AI 医生档案
--   DIABETES_HEALTH       健康档案与风险评估
--   DIABETES_CHECKIN      生活打卡
--   DIABETES_CONSULTATION 在线问诊
--   DIABETES_PLAN         健康方案
--   DIABETES_ARTICLE      健康资讯
--   DIABETES_AUDIT        审计日志
-- =============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- =============================================================================
-- DIABETES_RESOURCES
-- =============================================================================

CREATE DATABASE IF NOT EXISTS DIABETES_RESOURCES
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE DIABETES_RESOURCES;

CREATE TABLE IF NOT EXISTS BANNERS (
    BANNER_ID VARCHAR(32) PRIMARY KEY COMMENT '轮播图ID，如b1,b2,b3...',
    TITLE VARCHAR(100) NOT NULL DEFAULT '' COMMENT '标题',
    IS_DELETED TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除：0否 1是',
    DELETED_AT DATETIME DEFAULT NULL COMMENT '删除时间',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX IDX_IS_DELETED (IS_DELETED)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='轮播图表';

CREATE TABLE IF NOT EXISTS VIDEOS (
    VIDEO_ID VARCHAR(32) PRIMARY KEY COMMENT '视频ID,如v1,v2,v3...',
    TITLE VARCHAR(100) NOT NULL DEFAULT '' COMMENT '标题',
    DURATION TIME COMMENT '视频时长 hh:mm:ss',
    IS_DELETED TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除：0否 1是',
    DELETED_AT DATETIME DEFAULT NULL COMMENT '删除时间',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX IDX_IS_DELETED (IS_DELETED)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='视频表';



-- =============================================================================
-- DIABETES_USER
-- =============================================================================
CREATE DATABASE IF NOT EXISTS DIABETES_USER
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE DIABETES_USER;

CREATE TABLE USERS (
    USER_ID           VARCHAR(32)   PRIMARY KEY COMMENT '用户ID',
    USERNAME          VARCHAR(50)   NOT NULL UNIQUE COMMENT '登录用户名',
    PASSWORD_HASH     VARCHAR(255)  NOT NULL COMMENT 'bcrypt加密密码',
    PHONE             VARCHAR(20)   DEFAULT NULL COMMENT '手机号',
    EMAIL             VARCHAR(100)  DEFAULT NULL COMMENT '邮箱',
    AVATAR_ID         VARCHAR(200)  DEFAULT NULL COMMENT '头像MinIO对象名（profile桶），如 {userId}.jpg',
    NICKNAME          VARCHAR(100)  DEFAULT NULL COMMENT '昵称',
    GENDER            TINYINT       DEFAULT 0 COMMENT '性别：0=未知 1=男 2=女',
    BIRTH_DATE        DATE          DEFAULT NULL COMMENT '出生日期',
    POINTS            INT           DEFAULT 0 COMMENT '积分',
    PRIVACY_SETTINGS  JSON          DEFAULT NULL COMMENT '隐私设置JSON',
    IS_DELETED        TINYINT(1)    NOT NULL DEFAULT 0 COMMENT '是否删除：0否 1是',
    DELETED_AT        DATETIME      DEFAULT NULL COMMENT '删除时间',
    CREATED_AT        DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_AT        DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX IDX_PHONE (PHONE),
    INDEX IDX_IS_DELETED (IS_DELETED)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表';

CREATE TABLE ADMINS (
    ADMIN_ID          VARCHAR(32)   PRIMARY KEY COMMENT '管理员ID',
    USERNAME          VARCHAR(50)   NOT NULL UNIQUE COMMENT '登录用户名',
    PASSWORD_HASH     VARCHAR(255)  NOT NULL COMMENT 'bcrypt加密密码',
    IS_DELETED        TINYINT(1)    NOT NULL DEFAULT 0 COMMENT '是否删除：0否 1是',
    DELETED_AT        DATETIME      DEFAULT NULL COMMENT '删除时间',
    CREATED_AT        DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_AT        DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX IDX_IS_DELETED (IS_DELETED)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='管理员表';

-- 测试用户（明文密码均为 123456，bcrypt 加密存储）
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD_HASH, PHONE, NICKNAME, GENDER, BIRTH_DATE, POINTS, IS_DELETED) VALUES
('u_test001', 'testuser', '$2b$10$CPy7ORNm87/8zOinIhTlX.eZLWP1MPZm3UdW39JN1uIm3Qk51CN2u', '13800138000', '测试用户', 0, NULL, 0, 0),
('u_test002', 'zhangsan', '$2b$10$CPy7ORNm87/8zOinIhTlX.eZLWP1MPZm3UdW39JN1uIm3Qk51CN2u', '13900139001', '张三', 1, '1990-05-15', 100, 0),
('u_test003', 'lisi',     '$2b$10$CPy7ORNm87/8zOinIhTlX.eZLWP1MPZm3UdW39JN1uIm3Qk51CN2u', '13700137002', '李四', 2, '1988-11-20', 50, 0);

INSERT INTO ADMINS (ADMIN_ID, USERNAME, PASSWORD_HASH, IS_DELETED) VALUES
('adm_001', 'admin', '$2b$10$CPy7ORNm87/8zOinIhTlX.eZLWP1MPZm3UdW39JN1uIm3Qk51CN2u', 0);

CREATE TABLE USER_MESSAGES (
    MESSAGE_ID     VARCHAR(32)   NOT NULL PRIMARY KEY COMMENT '消息ID',
    USER_ID        VARCHAR(32)   NOT NULL COMMENT '用户ID',
    MESSAGE_TYPE   VARCHAR(32)   NOT NULL COMMENT 'risk_assess/plan_generate/consult_reply/checkin_analysis',
    STATUS         VARCHAR(16)   NOT NULL DEFAULT 'completed' COMMENT 'completed/failed',
    TITLE          VARCHAR(100)  NOT NULL COMMENT '标题',
    SUMMARY        VARCHAR(500)  DEFAULT NULL COMMENT '摘要/副文案',
    BIZ_ID         VARCHAR(64)   DEFAULT NULL COMMENT '业务主键',
    LINK_PATH      VARCHAR(200)  NOT NULL COMMENT '前端路由路径',
    LINK_QUERY     JSON          DEFAULT NULL COMMENT '路由 query 参数 JSON',
    EXTRA          JSON          DEFAULT NULL COMMENT '扩展字段',
    IS_READ        TINYINT(1)    NOT NULL DEFAULT 0 COMMENT '是否已读',
    READ_AT        DATETIME      DEFAULT NULL COMMENT '已读时间',
    EXPIRE_AT      DATETIME      DEFAULT NULL COMMENT '可选过期时间',
    CREATED_AT     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    INDEX IDX_USER_STATUS (USER_ID, IS_READ, STATUS, CREATED_AT DESC),
    INDEX IDX_USER_TYPE_BIZ (USER_ID, MESSAGE_TYPE, BIZ_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户消息中心';

-- =============================================================================
-- DIABETES_DOCTOR
-- =============================================================================
CREATE DATABASE IF NOT EXISTS DIABETES_DOCTOR
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE DIABETES_DOCTOR;

CREATE TABLE DOCTORS (
    DOCTOR_ID           VARCHAR(32)   PRIMARY KEY COMMENT '医生ID',
    NAME                VARCHAR(50)   NOT NULL COMMENT '医生姓名',
    TITLE               VARCHAR(50)   NOT NULL COMMENT '职称',
    DEPARTMENT          VARCHAR(50)   NOT NULL DEFAULT '待分配' COMMENT '科室',
    HOSPITAL            VARCHAR(100)  NOT NULL COMMENT '所属医院',
    AVATAR_ID          VARCHAR(500)  DEFAULT NULL COMMENT '头像ID',
    INTRODUCTION        TEXT          DEFAULT NULL COMMENT '个人简介',
    SPECIALTIES         JSON          DEFAULT NULL COMMENT '擅长领域JSON数组',
    RATING              DECIMAL(2,1)  DEFAULT 5.0 COMMENT '评分',
    CONSULTATION_COUNT  INT           DEFAULT 0 COMMENT '累计问诊次数',
    STATUS              TINYINT       DEFAULT 2 COMMENT '在线状态：1=在线 2=离线 3=忙碌',
    IS_DELETED          TINYINT(1)    NOT NULL DEFAULT 0 COMMENT '是否删除：0否 1是',
    DELETED_AT          DATETIME      DEFAULT NULL COMMENT '删除时间',
    CREATED_AT          DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_AT          DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX IDX_STATUS (STATUS),
    INDEX IDX_DEPARTMENT (DEPARTMENT),
    INDEX IDX_IS_DELETED (IS_DELETED)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI医生表';

INSERT INTO DOCTORS (DOCTOR_ID, NAME, TITLE, DEPARTMENT, HOSPITAL, AVATAR_ID, INTRODUCTION, SPECIALTIES, RATING, CONSULTATION_COUNT, STATUS) VALUES
('doc_001', '张明德', '主任医师', '内分泌科', '市第一人民医院', 'doc_001', '擅长2型糖尿病及并发症诊治，拥有丰富的临床经验。', '["2型糖尿病","并发症诊治"]', 4.9, 1280, 1),
('doc_002', '李雅琴', '副主任医师', '内分泌科', '市中心医院', 'doc_002', '糖尿病营养与运动干预专家，注重生活方式管理。', '["营养干预","运动管理"]', 4.8, 956, 1),
('doc_003', '王建国', '主治医师', '内分泌科', '省人民医院', 'doc_003', '糖尿病前期干预与健康管理，帮助患者科学控糖。', '["前期干预","健康管理"]', 4.7, 620, 2),
('doc_004', '陈丽华', '主任医师', '内分泌科', '协和医院', 'doc_004', '妊娠糖尿病及特殊人群管理，关注个体化诊疗。', '["妊娠糖尿病","特殊人群"]', 5.0, 2100, 3);

-- =============================================================================
-- DIABETES_HEALTH
-- =============================================================================
CREATE DATABASE IF NOT EXISTS DIABETES_HEALTH
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE DIABETES_HEALTH;

CREATE TABLE HEALTH_RECORDS (
    RECORD_ID             VARCHAR(32)   PRIMARY KEY COMMENT '档案ID',
    USER_ID               VARCHAR(32)   NOT NULL COMMENT '用户ID',
    HEIGHT                DECIMAL(5,1)  DEFAULT NULL COMMENT '身高(cm)',
    WEIGHT                DECIMAL(5,1)  DEFAULT NULL COMMENT '体重(kg)',
    BMI                   DECIMAL(4,1)  DEFAULT NULL COMMENT 'BMI',
    FASTING_GLUCOSE       DECIMAL(4,1)  DEFAULT NULL COMMENT '空腹血糖(mmol/L)',
    POSTPRANDIAL_GLUCOSE  DECIMAL(4,1)  DEFAULT NULL COMMENT '餐后2h血糖(mmol/L)',
    RANDOM_GLUCOSE        DECIMAL(4,1)  DEFAULT NULL COMMENT '随机血糖(mmol/L)',
    HBA1C                 DECIMAL(4,1)  DEFAULT NULL COMMENT '糖化血红蛋白(%)',
    SYSTOLIC_BP           DECIMAL(5,1)  DEFAULT NULL COMMENT '收缩压(mmHg)',
    DIASTOLIC_BP          DECIMAL(5,1)  DEFAULT NULL COMMENT '舒张压(mmHg)',
    DIABETES_TYPE         TINYINT       DEFAULT 9 COMMENT '糖尿病分型：0无 1前期 2一型 3二型 4妊娠 9未知',
    DIAGNOSED_DATE        DATE          DEFAULT NULL COMMENT '确诊日期',
    IS_PREGNANT           TINYINT       DEFAULT 0 COMMENT '是否妊娠：0否 1是（妊娠糖尿病评估用）',
    HAS_DIABETES_FAMILY   TINYINT       DEFAULT 0 COMMENT '糖尿病家族史：0无 1有',
    IS_INSULIN_TAKEN      TINYINT       DEFAULT 0 COMMENT '是否使用胰岛素：0否 1是',
    SMOKING               TINYINT       DEFAULT NULL COMMENT '吸烟：0从不 1曾经 2当前',
    ALCOHOL               TINYINT       DEFAULT NULL COMMENT '饮酒：0从不 1偶尔 2规律',
    EXERCISE_FREQ         TINYINT       DEFAULT NULL COMMENT '运动频率：0-3',
    DIET_TYPE             VARCHAR(100)  DEFAULT NULL COMMENT '饮食习惯',
    TEST_SOURCE           TINYINT       DEFAULT 1 COMMENT '数据来源：1自测 2医院',
    RECORDED_AT           DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT '录入时间',
    UPDATED_AT            DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    CREATE_USER           VARCHAR(32)   DEFAULT NULL COMMENT '录入操作人ID',
    DEL_FLAG              TINYINT       DEFAULT 0 COMMENT '逻辑删除：0正常 1已删除',
    FOREIGN KEY (USER_ID) REFERENCES DIABETES_USER.USERS(USER_ID) ON DELETE CASCADE,
    INDEX IDX_USER_RECORD (USER_ID, RECORDED_AT DESC, DEL_FLAG),
    INDEX IDX_DIABETES_RISK (DEL_FLAG, DIABETES_TYPE, HAS_DIABETES_FAMILY, BMI),
    INDEX IDX_GLUCOSE_CHECK (DEL_FLAG, FASTING_GLUCOSE, POSTPRANDIAL_GLUCOSE, HBA1C)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='健康档案主表';

CREATE TABLE HEALTH_RECORD_MEDICAL_HISTORIES (
    HISTORY_ID        VARCHAR(32)   PRIMARY KEY COMMENT '病史ID',
    RECORD_ID         VARCHAR(32)   NOT NULL COMMENT '档案ID',
    USER_ID           VARCHAR(32)   NOT NULL COMMENT '用户ID',
    DISEASE_CODE      VARCHAR(32)   DEFAULT NULL COMMENT '疾病编码',
    DISEASE_NAME      VARCHAR(100)  NOT NULL COMMENT '疾病名称',
    DIAGNOSED_DATE    DATE          DEFAULT NULL COMMENT '确诊日期',
    STATUS            TINYINT       DEFAULT 1 COMMENT '病程：1进行中 2已控制 3已治愈',
    NOTE              VARCHAR(500)  DEFAULT NULL COMMENT '补充说明',
    SOURCE            TINYINT       DEFAULT 1 COMMENT '来源：1自报 2AI解析',
    DEL_FLAG          TINYINT       DEFAULT 0 COMMENT '逻辑删除',
    CREATED_AT        DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_AT        DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY (RECORD_ID) REFERENCES HEALTH_RECORDS(RECORD_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES DIABETES_USER.USERS(USER_ID) ON DELETE CASCADE,
    INDEX IDX_RECORD (RECORD_ID, DEL_FLAG),
    INDEX IDX_USER (USER_ID, DEL_FLAG),
    INDEX IDX_DISEASE (DISEASE_CODE, DEL_FLAG)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='既往病史子表';

CREATE TABLE HEALTH_RECORD_MEDICATIONS (
    MEDICATION_ID     VARCHAR(32)   PRIMARY KEY COMMENT '用药ID',
    RECORD_ID         VARCHAR(32)   NOT NULL COMMENT '档案ID',
    USER_ID           VARCHAR(32)   NOT NULL COMMENT '用户ID',
    DRUG_NAME         VARCHAR(100)  NOT NULL COMMENT '药品名称',
    GENERIC_NAME      VARCHAR(100)  DEFAULT NULL COMMENT '通用名',
    DOSAGE            VARCHAR(50)   DEFAULT NULL COMMENT '剂量',
    FREQUENCY         VARCHAR(20)   DEFAULT NULL COMMENT '频次编码',
    FREQUENCY_DESC    VARCHAR(100)  DEFAULT NULL COMMENT '服用说明',
    ROUTE             VARCHAR(20)   DEFAULT NULL COMMENT '给药途径',
    PURPOSE           VARCHAR(50)   DEFAULT NULL COMMENT '用途',
    IS_INSULIN        TINYINT       DEFAULT 0 COMMENT '是否胰岛素',
    START_DATE        DATE          DEFAULT NULL COMMENT '开始日期',
    END_DATE          DATE          DEFAULT NULL COMMENT '结束日期',
    STATUS            TINYINT       DEFAULT 1 COMMENT '状态：1在用 2停用',
    SOURCE            TINYINT       DEFAULT 1 COMMENT '来源',
    DEL_FLAG          TINYINT       DEFAULT 0 COMMENT '逻辑删除',
    CREATED_AT        DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_AT        DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY (RECORD_ID) REFERENCES HEALTH_RECORDS(RECORD_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES DIABETES_USER.USERS(USER_ID) ON DELETE CASCADE,
    INDEX IDX_RECORD (RECORD_ID, DEL_FLAG),
    INDEX IDX_USER (USER_ID, DEL_FLAG),
    INDEX IDX_INSULIN (RECORD_ID, IS_INSULIN, STATUS, DEL_FLAG),
    INDEX IDX_DRUG (DRUG_NAME, DEL_FLAG)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用药明细子表';

CREATE TABLE HEALTH_RECORD_FAMILY_HISTORIES (
    FAMILY_HISTORY_ID VARCHAR(32)   PRIMARY KEY COMMENT '家族病史ID',
    RECORD_ID         VARCHAR(32)   NOT NULL COMMENT '档案ID',
    USER_ID           VARCHAR(32)   NOT NULL COMMENT '用户ID',
    RELATION          VARCHAR(20)   NOT NULL COMMENT '亲属关系',
    MEMBER_AGE        TINYINT       DEFAULT NULL COMMENT '亲属年龄',
    IS_ALIVE          TINYINT       DEFAULT 1 COMMENT '是否健在',
    DISEASE_CODE      VARCHAR(32)   DEFAULT NULL COMMENT '疾病编码',
    DISEASE_NAME      VARCHAR(100)  NOT NULL COMMENT '疾病名称',
    DIAGNOSED_AGE     TINYINT       DEFAULT NULL COMMENT '确诊年龄',
    IS_DIABETES       TINYINT       DEFAULT 0 COMMENT '是否糖尿病相关',
    NOTE              VARCHAR(500)  DEFAULT NULL COMMENT '补充说明',
    SOURCE            TINYINT       DEFAULT 1 COMMENT '来源',
    DEL_FLAG          TINYINT       DEFAULT 0 COMMENT '逻辑删除',
    CREATED_AT        DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_AT        DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY (RECORD_ID) REFERENCES HEALTH_RECORDS(RECORD_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES DIABETES_USER.USERS(USER_ID) ON DELETE CASCADE,
    INDEX IDX_RECORD (RECORD_ID, DEL_FLAG),
    INDEX IDX_USER (USER_ID, DEL_FLAG),
    INDEX IDX_DIABETES (RECORD_ID, IS_DIABETES, DEL_FLAG)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='家族病史子表';

CREATE TABLE RISK_ASSESSMENTS (
    ASSESSMENT_ID         VARCHAR(32)   PRIMARY KEY COMMENT '评估ID',
    USER_ID               VARCHAR(32)   NOT NULL COMMENT '用户ID',
    HEALTH_RECORD_ID      VARCHAR(32)   NOT NULL COMMENT '关联健康档案ID',
    DIFY_WORKFLOW_ID      VARCHAR(64)   DEFAULT NULL COMMENT 'Dify工作流运行ID',
    RISK_LEVEL            TINYINT       NOT NULL COMMENT '风险等级：1低 2中 3高',
    RISK_SCORE            INT           NOT NULL COMMENT '风险分值0-100',
    BMI_SNAPSHOT          DECIMAL(4,1)  DEFAULT NULL COMMENT 'BMI快照',
    GLUCOSE_LEVEL         TINYINT       DEFAULT NULL COMMENT '血糖等级：1正常 2前期 3糖尿病',
    CONFIDENCE            TINYINT       DEFAULT 2 COMMENT '置信度：1低 2中 3高',
    GENERATION_STATUS     TINYINT       DEFAULT 2 COMMENT '状态：1评估中 2完成 3失败',
    REPORT_SUMMARY        VARCHAR(500)  DEFAULT NULL COMMENT '报告摘要',
    AI_RAW_RESPONSE       JSON          DEFAULT NULL COMMENT 'AI原始输出',
    DEL_FLAG              TINYINT       DEFAULT 0 COMMENT '逻辑删除',
    ASSESSED_AT           DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT '评估时间',
    CREATED_AT            DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_AT            DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY (USER_ID) REFERENCES DIABETES_USER.USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (HEALTH_RECORD_ID) REFERENCES HEALTH_RECORDS(RECORD_ID) ON DELETE CASCADE,
    INDEX IDX_USER_ASSESSMENT (USER_ID, DEL_FLAG, ASSESSED_AT DESC),
    INDEX IDX_USER_LEVEL (USER_ID, RISK_LEVEL, DEL_FLAG),
    INDEX IDX_RECORD (HEALTH_RECORD_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='风险评估主表';

CREATE TABLE RISK_ASSESSMENT_FACTORS (
    FACTOR_ID         VARCHAR(32)   PRIMARY KEY COMMENT '因素ID',
    ASSESSMENT_ID     VARCHAR(32)   NOT NULL COMMENT '评估ID',
    FACTOR_CODE       VARCHAR(32)   DEFAULT NULL COMMENT '因素编码',
    FACTOR_NAME       VARCHAR(100)  NOT NULL COMMENT '因素名称',
    WEIGHT            DECIMAL(5,2)  DEFAULT NULL COMMENT '权重0-100',
    FACTOR_LEVEL      TINYINT       DEFAULT NULL COMMENT '因素等级',
    DESCRIPTION       VARCHAR(500)  DEFAULT NULL COMMENT '说明',
    SORT_ORDER        TINYINT       DEFAULT 0 COMMENT '排序',
    DEL_FLAG          TINYINT       DEFAULT 0 COMMENT '逻辑删除',
    FOREIGN KEY (ASSESSMENT_ID) REFERENCES RISK_ASSESSMENTS(ASSESSMENT_ID) ON DELETE CASCADE,
    INDEX IDX_ASSESSMENT (ASSESSMENT_ID, DEL_FLAG, SORT_ORDER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='风险因素明细';

CREATE TABLE RISK_ASSESSMENT_SUGGESTIONS (
    SUGGESTION_ID     VARCHAR(32)   PRIMARY KEY COMMENT '建议ID',
    ASSESSMENT_ID     VARCHAR(32)   NOT NULL COMMENT '评估ID',
    CATEGORY          TINYINT       DEFAULT 1 COMMENT '类别：1饮食 2运动 3生活 4就医',
    PRIORITY          TINYINT       DEFAULT 2 COMMENT '优先级：1高 2中 3低',
    CONTENT           TEXT          NOT NULL COMMENT '建议内容',
    SORT_ORDER        TINYINT       DEFAULT 0 COMMENT '排序',
    DEL_FLAG          TINYINT       DEFAULT 0 COMMENT '逻辑删除',
    FOREIGN KEY (ASSESSMENT_ID) REFERENCES RISK_ASSESSMENTS(ASSESSMENT_ID) ON DELETE CASCADE,
    INDEX IDX_ASSESSMENT (ASSESSMENT_ID, DEL_FLAG, PRIORITY, SORT_ORDER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='改善建议明细';

-- =============================================================================
-- DIABETES_CHECKIN
-- =============================================================================
CREATE DATABASE IF NOT EXISTS DIABETES_CHECKIN
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE DIABETES_CHECKIN;

CREATE TABLE CHECKIN_RECORDS (
    CHECKIN_ID        VARCHAR(32)   PRIMARY KEY COMMENT '打卡ID',
    USER_ID           VARCHAR(32)   NOT NULL COMMENT '用户ID',
    CHECKIN_TYPE      TINYINT       NOT NULL COMMENT '类型：1饮食 2运动 3用药 4血糖 5血压 6体重 7复诊',
    CHECKIN_DATE      DATE          NOT NULL COMMENT '归属日期',
    RECORD_TIME       DATETIME      NOT NULL COMMENT '实际测量时间',
    POINTS_EARNED     INT           DEFAULT 0 COMMENT '获得积分',
    POINTS_SOURCE     TINYINT       DEFAULT 1 COMMENT '积分来源',
    ABNORMAL_TYPE     TINYINT       DEFAULT 0 COMMENT '异常类型：0正常',
    STREAK_DAYS       INT           DEFAULT 0 COMMENT '连续打卡天数快照',
    DEL_FLAG          TINYINT       DEFAULT 0 COMMENT '逻辑删除',
    CREATED_AT        DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_AT        DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY (USER_ID) REFERENCES DIABETES_USER.USERS(USER_ID) ON DELETE CASCADE,
    INDEX IDX_USER_DATE (USER_ID, CHECKIN_DATE DESC, DEL_FLAG),
    INDEX IDX_USER_TYPE_DATE (USER_ID, CHECKIN_TYPE, CHECKIN_DATE, DEL_FLAG),
    INDEX IDX_RECORD_TIME (USER_ID, RECORD_TIME DESC),
    INDEX IDX_ABNORMAL (DEL_FLAG, ABNORMAL_TYPE, CHECKIN_DATE),
    INDEX IDX_POINTS_SOURCE (USER_ID, POINTS_SOURCE, CHECKIN_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='打卡主表';

-- 健康打卡预设基础数据（见 docs/健康打卡模块产品设计说明书.md v1.2）
-- MinIO bucket=checkin，图片 Object Key：food/{FOOD_ID}.jpg、medical/{DRUG_ID}.jpg

CREATE TABLE FOOD_CATEGORIES (
    CATEGORY_ID       VARCHAR(32)   PRIMARY KEY COMMENT '分类ID',
    CATEGORY_NAME     VARCHAR(50)   NOT NULL COMMENT '分类名称',
    DEL_FLAG          TINYINT       DEFAULT 0 COMMENT '逻辑删除：0正常 1删除',
    CREATED_AT        DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_AT        DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY UK_CATEGORY_NAME (CATEGORY_NAME, DEL_FLAG),
    INDEX IDX_CATEGORY_DEL (DEL_FLAG, CATEGORY_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='食物分类（系统预录入）';

CREATE TABLE FOOD_PRESETS (
    FOOD_ID           VARCHAR(32)   PRIMARY KEY COMMENT '食物ID（MinIO 图片：food/{FOOD_ID}.jpg）',
    CATEGORY_ID       VARCHAR(32)   NOT NULL COMMENT '所属分类ID',
    FOOD_NAME         VARCHAR(100)  NOT NULL COMMENT '食物名称',
    CALORIES_PER_GRAM DECIMAL(8,4)  NOT NULL COMMENT '每克卡路里 kcal/g',
    IS_LIQUID         TINYINT       DEFAULT 0 COMMENT '是否液体类：0否 1是',
    ML_TO_G_RATIO     DECIMAL(6,4)  DEFAULT 1.0000 COMMENT 'ml→g 换算系数：克数=毫升数×系数',
    DEL_FLAG          TINYINT       DEFAULT 0 COMMENT '逻辑删除',
    CREATED_AT        DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_AT        DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY (CATEGORY_ID) REFERENCES FOOD_CATEGORIES(CATEGORY_ID),
    INDEX IDX_FOOD_CATEGORY (CATEGORY_ID, DEL_FLAG, FOOD_NAME),
    INDEX IDX_FOOD_NAME (FOOD_NAME, DEL_FLAG)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统预设食物';

CREATE TABLE MEDICATION_PRESETS (
    DRUG_ID           VARCHAR(32)   PRIMARY KEY COMMENT '药品ID（MinIO 图片：medical/{DRUG_ID}.jpg）',
    DRUG_NAME         VARCHAR(100)  NOT NULL COMMENT '药品名称',
    DEL_FLAG          TINYINT       DEFAULT 0 COMMENT '逻辑删除',
    CREATED_AT        DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_AT        DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX IDX_DRUG_NAME (DRUG_NAME, DEL_FLAG)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统预设药品';

CREATE TABLE EXERCISE_PRESETS (
    EXERCISE_ID         VARCHAR(32)   PRIMARY KEY COMMENT '运动ID',
    EXERCISE_NAME       VARCHAR(50)   NOT NULL COMMENT '运动项目名称',
    CALORIES_PER_MINUTE DECIMAL(8,2)  NOT NULL COMMENT '每分钟消耗 kcal/min',
    DEL_FLAG            TINYINT       DEFAULT 0 COMMENT '逻辑删除',
    CREATED_AT          DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_AT          DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX IDX_EXERCISE_NAME (EXERCISE_NAME, DEL_FLAG)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统预设运动';

CREATE TABLE CHECKIN_DIET_DETAILS (
    CHECKIN_ID        VARCHAR(32)   PRIMARY KEY COMMENT '打卡ID',
    MEAL_PERIOD       TINYINT       NOT NULL COMMENT '餐次：1早餐 2午餐 3晚餐 4上午加餐 5下午加餐 6晚上加餐',
    SOURCE_TYPE       TINYINT       NOT NULL COMMENT '来源：1选用预设 2自定义',
    FOOD_ID           VARCHAR(32)   DEFAULT NULL COMMENT '预设食物ID',
    FOOD_NAME         VARCHAR(100)  NOT NULL COMMENT '食物名称',
    CATEGORY_NAME     VARCHAR(50)   DEFAULT NULL COMMENT '分类名称（展示冗余）',
    CALORIES_PER_GRAM DECIMAL(8,4)  NOT NULL COMMENT '每克卡路里 kcal/g',
    INPUT_UNIT        TINYINT       NOT NULL DEFAULT 1 COMMENT '录入单位：1=g 2=ml',
    INPUT_AMOUNT      DECIMAL(8,2)  NOT NULL COMMENT '用户原始录入量（g或ml）',
    GRAMS             DECIMAL(8,2)  NOT NULL COMMENT '换算后食用克数',
    TOTAL_CALORIES    INT           NOT NULL COMMENT '总热量 kcal',
    IMAGE_OBJECT_KEY  VARCHAR(200)  NOT NULL COMMENT 'MinIO Object Key，如 food/{ID}.jpg',
    FOREIGN KEY (CHECKIN_ID) REFERENCES CHECKIN_RECORDS(CHECKIN_ID) ON DELETE CASCADE,
    FOREIGN KEY (FOOD_ID) REFERENCES FOOD_PRESETS(FOOD_ID) ON DELETE SET NULL,
    INDEX IDX_DIET_FOOD (FOOD_ID),
    INDEX IDX_DIET_MEAL (MEAL_PERIOD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='饮食打卡明细';

CREATE TABLE CHECKIN_EXERCISE_DETAILS (
    CHECKIN_ID          VARCHAR(32)   PRIMARY KEY COMMENT '打卡ID',
    SOURCE_TYPE         TINYINT       NOT NULL COMMENT '来源：1选用预设 2自定义',
    EXERCISE_ID         VARCHAR(32)   DEFAULT NULL COMMENT '预设运动ID',
    EXERCISE_NAME       VARCHAR(50)   NOT NULL COMMENT '运动项目名称',
    CALORIES_PER_MINUTE DECIMAL(8,2)  NOT NULL COMMENT '每分钟消耗 kcal/min',
    DURATION_MINUTES    INT           NOT NULL COMMENT '时长分钟',
    CALORIES_BURNED     INT           DEFAULT NULL COMMENT '总消耗 kcal = round(kcal/min × 分钟数)',
    FOREIGN KEY (CHECKIN_ID) REFERENCES CHECKIN_RECORDS(CHECKIN_ID) ON DELETE CASCADE,
    FOREIGN KEY (EXERCISE_ID) REFERENCES EXERCISE_PRESETS(EXERCISE_ID) ON DELETE SET NULL,
    INDEX IDX_EXERCISE_ID (EXERCISE_ID),
    INDEX IDX_DURATION (DURATION_MINUTES)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='运动打卡明细';

CREATE TABLE CHECKIN_MEDICATION_DETAILS (
    CHECKIN_ID        VARCHAR(32)   PRIMARY KEY COMMENT '打卡ID',
    SOURCE_TYPE       TINYINT       NOT NULL COMMENT '来源：1选用预设 2自定义',
    DRUG_ID           VARCHAR(32)   DEFAULT NULL COMMENT '预设药品ID',
    DRUG_NAME         VARCHAR(100)  NOT NULL COMMENT '药品名称',
    DOSAGE            VARCHAR(50)   DEFAULT NULL COMMENT '剂量',
    TAKEN             TINYINT       DEFAULT 1 COMMENT '是否已服：1是 0否',
    IMAGE_OBJECT_KEY  VARCHAR(200)  NOT NULL COMMENT 'MinIO Object Key，如 medical/{ID}.jpg',
    FOREIGN KEY (CHECKIN_ID) REFERENCES CHECKIN_RECORDS(CHECKIN_ID) ON DELETE CASCADE,
    FOREIGN KEY (DRUG_ID) REFERENCES MEDICATION_PRESETS(DRUG_ID) ON DELETE SET NULL,
    INDEX IDX_MED_DRUG_ID (DRUG_ID),
    INDEX IDX_DRUG (DRUG_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用药打卡明细';

CREATE TABLE CHECKIN_GLUCOSE_DETAILS (
    CHECKIN_ID        VARCHAR(32)   PRIMARY KEY COMMENT '打卡ID',
    GLUCOSE_VALUE     DECIMAL(4,1)  NOT NULL COMMENT '血糖值',
    MEASURE_CONTEXT   TINYINT       NOT NULL COMMENT '时段：1空腹 2餐后2h 3睡前 4随机',
    UNIT              TINYINT       DEFAULT 1 COMMENT '单位：1mmol/L 2mg/dL',
    FOREIGN KEY (CHECKIN_ID) REFERENCES CHECKIN_RECORDS(CHECKIN_ID) ON DELETE CASCADE,
    INDEX IDX_GLUCOSE_VALUE (GLUCOSE_VALUE),
    INDEX IDX_CONTEXT (MEASURE_CONTEXT, GLUCOSE_VALUE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='血糖打卡明细';

CREATE TABLE CHECKIN_BP_DETAILS (
    CHECKIN_ID        VARCHAR(32)   PRIMARY KEY COMMENT '打卡ID',
    SYSTOLIC_BP       DECIMAL(5,1)  NOT NULL COMMENT '收缩压',
    DIASTOLIC_BP      DECIMAL(5,1)  NOT NULL COMMENT '舒张压',
    PULSE             INT           DEFAULT NULL COMMENT '脉搏',
    MEASURE_CONTEXT   TINYINT       DEFAULT 1 COMMENT '测量时段',
    FOREIGN KEY (CHECKIN_ID) REFERENCES CHECKIN_RECORDS(CHECKIN_ID) ON DELETE CASCADE,
    INDEX IDX_SYSTOLIC (SYSTOLIC_BP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='血压打卡明细';

CREATE TABLE CHECKIN_WEIGHT_DETAILS (
    CHECKIN_ID        VARCHAR(32)   PRIMARY KEY COMMENT '打卡ID',
    WEIGHT            DECIMAL(5,1)  NOT NULL COMMENT '体重kg',
    BODY_FAT_RATE     DECIMAL(4,1)  DEFAULT NULL COMMENT '体脂率',
    FOREIGN KEY (CHECKIN_ID) REFERENCES CHECKIN_RECORDS(CHECKIN_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='体重打卡明细';

-- 打卡提醒（见 docs/打卡提醒模块产品设计说明书.md）
CREATE TABLE CHECKIN_REMINDER_RULES (
    RULE_ID        VARCHAR(32)  NOT NULL PRIMARY KEY COMMENT '规则ID',
    USER_ID        VARCHAR(32)  NOT NULL COMMENT '用户ID',
    CHECKIN_TYPE   TINYINT      NOT NULL COMMENT '1饮食 2运动 3用药 4血糖',
    REMIND_TIME    TIME         NOT NULL COMMENT '每日提醒时刻 HH:mm:ss',
    ENABLED        TINYINT(1)   NOT NULL DEFAULT 1 COMMENT '是否启用',
    SORT_ORDER     INT          NOT NULL DEFAULT 0 COMMENT '排序',
    CREATED_AT     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_AT     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY (USER_ID) REFERENCES DIABETES_USER.USERS(USER_ID) ON DELETE CASCADE,
    INDEX IDX_USER_TYPE (USER_ID, CHECKIN_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='打卡提醒规则';

CREATE TABLE CHECKIN_REMINDER_LOGS (
    LOG_ID         VARCHAR(32)  NOT NULL PRIMARY KEY COMMENT '日志ID',
    USER_ID        VARCHAR(32)  NOT NULL COMMENT '用户ID',
    RULE_ID        VARCHAR(32)  NOT NULL COMMENT '规则ID',
    CHECKIN_TYPE   TINYINT      NOT NULL COMMENT '1饮食 2运动 3用药 4血糖',
    REMIND_DATE    DATE         NOT NULL COMMENT '提醒归属日期',
    CHANNEL        VARCHAR(32)  NOT NULL DEFAULT 'in_app' COMMENT 'in_app/browser_push/in_page_banner',
    STATUS         TINYINT      NOT NULL DEFAULT 0 COMMENT '0已发送 1已点击 2已忽略 3snooze',
    SNOOZE_UNTIL   DATETIME     DEFAULT NULL COMMENT '稍后提醒截止时间',
    SNOOZE_COUNT   INT          NOT NULL DEFAULT 0 COMMENT '当日稍后提醒次数',
    CREATED_AT     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_AT     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY (USER_ID) REFERENCES DIABETES_USER.USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (RULE_ID) REFERENCES CHECKIN_REMINDER_RULES(RULE_ID) ON DELETE CASCADE,
    UNIQUE KEY UK_RULE_DATE (RULE_ID, REMIND_DATE),
    INDEX IDX_USER_DATE (USER_ID, REMIND_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='打卡提醒触达日志';

-- 健康打卡预设种子数据（MinIO 需另行上传对应 jpg 图片）
INSERT INTO FOOD_CATEGORIES (CATEGORY_ID, CATEGORY_NAME) VALUES
    ('cat_drink',   '饮品'),
    ('cat_fruit',   '水果'),
    ('cat_grain',   '主食'),
    ('cat_protein', '蛋白'),
    ('cat_veg',     '蔬菜');

INSERT INTO FOOD_PRESETS (FOOD_ID, CATEGORY_ID, FOOD_NAME, CALORIES_PER_GRAM, IS_LIQUID, ML_TO_G_RATIO) VALUES
    ('food_milk_001',  'cat_drink',   '牛奶',   0.5400, 1, 1.0300),
    ('food_rice_001',  'cat_grain',   '糙米饭', 1.1600, 0, 1.0000),
    ('food_egg_001',   'cat_protein', '鸡蛋白', 0.5200, 0, 1.0000),
    ('food_apple_001', 'cat_fruit',   '苹果',   0.5200, 0, 1.0000);

INSERT INTO MEDICATION_PRESETS (DRUG_ID, DRUG_NAME) VALUES
    ('drug_metformin_001', '二甲双胍片'),
    ('drug_glimepiride_001', '格列美脲片');

INSERT INTO EXERCISE_PRESETS (EXERCISE_ID, EXERCISE_NAME, CALORIES_PER_MINUTE) VALUES
    ('ex_walk_001',  '快走', 4.50),
    ('ex_jog_001',   '慢跑', 7.00),
    ('ex_swim_001',  '游泳', 8.00);

-- =============================================================================
-- DIABETES_CONSULTATION
-- =============================================================================
CREATE DATABASE IF NOT EXISTS DIABETES_CONSULTATION
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE DIABETES_CONSULTATION;

CREATE TABLE CONSULTATION_SESSIONS (
    SESSION_ID            VARCHAR(32)   PRIMARY KEY COMMENT '会话ID',
    USER_ID               VARCHAR(32)   NOT NULL COMMENT '用户ID',
    DOCTOR_ID             VARCHAR(32)   NOT NULL COMMENT 'AI医生ID',
    DIFY_CONVERSATION_ID  VARCHAR(64)   DEFAULT NULL COMMENT 'Dify对话ID',
    DIFY_WORKFLOW_ID      VARCHAR(64)   DEFAULT NULL COMMENT 'Dify工作流ID',
    STATUS                TINYINT       DEFAULT 1 COMMENT '状态：1进行中 2已结束',
    TITLE                 VARCHAR(200)  DEFAULT NULL COMMENT '会话标题',
    INITIAL_MESSAGE       TEXT          DEFAULT NULL COMMENT '初始问题',
    LAST_MESSAGE          VARCHAR(500)  DEFAULT NULL COMMENT '最后消息摘要',
    LAST_MESSAGE_AT       DATETIME      DEFAULT NULL COMMENT '最后消息时间',
    MESSAGE_COUNT         INT           DEFAULT 0 COMMENT '消息数',
    RATING                TINYINT       DEFAULT NULL COMMENT '评分1-5',
    FEEDBACK              TEXT          DEFAULT NULL COMMENT '评价',
    CLOSE_REASON          TINYINT       DEFAULT NULL COMMENT '结束原因',
    STARTED_AT            DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT '开始时间',
    ENDED_AT              DATETIME      DEFAULT NULL COMMENT '结束时间',
    DEL_FLAG              TINYINT       DEFAULT 0 COMMENT '逻辑删除',
    CREATED_AT            DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_AT            DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY (USER_ID) REFERENCES DIABETES_USER.USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (DOCTOR_ID) REFERENCES DIABETES_DOCTOR.DOCTORS(DOCTOR_ID) ON DELETE CASCADE,
    INDEX IDX_USER_SESSION (USER_ID, STARTED_AT DESC, DEL_FLAG),
    INDEX IDX_USER_STATUS (USER_ID, STATUS, DEL_FLAG, LAST_MESSAGE_AT DESC),
    INDEX IDX_DOCTOR_SESSION (DOCTOR_ID, STARTED_AT DESC, DEL_FLAG),
    INDEX IDX_DIFY_CONV (DIFY_CONVERSATION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='问诊会话表';

CREATE TABLE CONSULTATION_MESSAGES (
    MESSAGE_ID        VARCHAR(32)   PRIMARY KEY COMMENT '消息ID',
    SESSION_ID        VARCHAR(32)   NOT NULL COMMENT '会话ID',
    SENDER_TYPE       TINYINT       NOT NULL COMMENT '发送者：1用户 2AI医生 3系统',
    SENDER_ID         VARCHAR(32)   DEFAULT NULL COMMENT '发送者ID',
    MESSAGE_TYPE      TINYINT       DEFAULT 1 COMMENT '类型：1文本 2图片 3语音 4系统',
    CONTENT           TEXT          DEFAULT NULL COMMENT '消息内容',
    IS_AI_GENERATED   TINYINT       DEFAULT 0 COMMENT '是否AI生成',
    AI_METADATA       JSON          DEFAULT NULL COMMENT 'AI元数据',
    IS_READ           TINYINT       DEFAULT 0 COMMENT '是否已读',
    READ_AT           DATETIME      DEFAULT NULL COMMENT '已读时间',
    DEL_FLAG          TINYINT       DEFAULT 0 COMMENT '逻辑删除',
    SENT_AT           DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间',
    UPDATED_AT        DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY (SESSION_ID) REFERENCES CONSULTATION_SESSIONS(SESSION_ID) ON DELETE CASCADE,
    INDEX IDX_SESSION_TIME (SESSION_ID, SENT_AT ASC, DEL_FLAG),
    INDEX IDX_SESSION_UNREAD (SESSION_ID, IS_READ, DEL_FLAG)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='问诊消息表';

CREATE TABLE CONSULTATION_MESSAGE_ATTACHMENTS (
    ATTACHMENT_ID     VARCHAR(32)   PRIMARY KEY COMMENT '附件ID',
    MESSAGE_ID        VARCHAR(32)   NOT NULL COMMENT '消息ID',
    FILE_URL          VARCHAR(500)  NOT NULL COMMENT '文件URL',
    FILE_TYPE         TINYINT       DEFAULT 1 COMMENT '文件类型',
    FILE_NAME         VARCHAR(200)  DEFAULT NULL COMMENT '文件名',
    FILE_SIZE         INT           DEFAULT NULL COMMENT '文件大小',
    SORT_ORDER        TINYINT       DEFAULT 0 COMMENT '排序',
    DEL_FLAG          TINYINT       DEFAULT 0 COMMENT '逻辑删除',
    CREATED_AT        DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT '上传时间',
    FOREIGN KEY (MESSAGE_ID) REFERENCES CONSULTATION_MESSAGES(MESSAGE_ID) ON DELETE CASCADE,
    INDEX IDX_MESSAGE (MESSAGE_ID, DEL_FLAG, SORT_ORDER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='问诊消息附件表';

-- =============================================================================
-- DIABETES_PLAN
-- =============================================================================
CREATE DATABASE IF NOT EXISTS DIABETES_PLAN
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE DIABETES_PLAN;

CREATE TABLE HEALTH_PLANS (
    PLAN_ID               VARCHAR(32)   PRIMARY KEY COMMENT '方案ID',
    USER_ID               VARCHAR(32)   NOT NULL COMMENT '用户ID',
    HEALTH_RECORD_ID      VARCHAR(32)   DEFAULT NULL COMMENT '健康档案ID',
    RISK_ASSESSMENT_ID    VARCHAR(32)   DEFAULT NULL COMMENT '风险评估ID',
    SESSION_ID            VARCHAR(32)   DEFAULT NULL COMMENT '问诊会话ID',
    DIFY_WORKFLOW_ID      VARCHAR(64)   DEFAULT NULL COMMENT 'Dify工作流ID',
    TITLE                 VARCHAR(200)  DEFAULT NULL COMMENT '方案标题',
    SUMMARY               VARCHAR(500)  DEFAULT NULL COMMENT '方案概述',
    DAILY_CALORIES        INT           NOT NULL COMMENT '每日热量kcal',
    MEDICATION_NOTE       TEXT          DEFAULT NULL COMMENT '用药提醒',
    SOURCE                TINYINT       DEFAULT 1 COMMENT '来源：1手动 2评估 3问诊 4自动',
    VERSION               INT           DEFAULT 1 COMMENT '版本号',
    IS_ACTIVE             TINYINT       DEFAULT 1 COMMENT '是否生效',
    IS_FAVORITE           TINYINT       DEFAULT 0 COMMENT '是否收藏',
    AI_RAW_RESPONSE       JSON          DEFAULT NULL COMMENT 'AI原始输出',
    DEL_FLAG              TINYINT       DEFAULT 0 COMMENT '逻辑删除',
    GENERATED_AT          DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT '生成时间',
    CREATED_AT            DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_AT            DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY (USER_ID) REFERENCES DIABETES_USER.USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (HEALTH_RECORD_ID) REFERENCES DIABETES_HEALTH.HEALTH_RECORDS(RECORD_ID) ON DELETE SET NULL,
    FOREIGN KEY (RISK_ASSESSMENT_ID) REFERENCES DIABETES_HEALTH.RISK_ASSESSMENTS(ASSESSMENT_ID) ON DELETE SET NULL,
    FOREIGN KEY (SESSION_ID) REFERENCES DIABETES_CONSULTATION.CONSULTATION_SESSIONS(SESSION_ID) ON DELETE SET NULL,
    INDEX IDX_USER_ACTIVE (USER_ID, IS_ACTIVE, DEL_FLAG, GENERATED_AT DESC),
    INDEX IDX_USER_HISTORY (USER_ID, DEL_FLAG, GENERATED_AT DESC),
    INDEX IDX_SOURCE (USER_ID, SOURCE, DEL_FLAG)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='健康方案主表';

CREATE TABLE HEALTH_PLAN_DIET_ITEMS (
    ITEM_ID           VARCHAR(32)   PRIMARY KEY COMMENT '明细ID',
    PLAN_ID           VARCHAR(32)   NOT NULL COMMENT '方案ID',
    MEAL_PERIOD       TINYINT       NOT NULL COMMENT '餐次',
    FOOD_NAME         VARCHAR(100)  NOT NULL COMMENT '食物名称',
    PORTION           VARCHAR(50)   DEFAULT NULL COMMENT '份量',
    CALORIES          INT           DEFAULT NULL COMMENT '热量',
    GI_VALUE          DECIMAL(4,1)  DEFAULT NULL COMMENT 'GI值',
    NOTE              VARCHAR(500)  DEFAULT NULL COMMENT '备注',
    SORT_ORDER        TINYINT       DEFAULT 0 COMMENT '排序',
    DEL_FLAG          TINYINT       DEFAULT 0 COMMENT '逻辑删除',
    FOREIGN KEY (PLAN_ID) REFERENCES HEALTH_PLANS(PLAN_ID) ON DELETE CASCADE,
    INDEX IDX_PLAN_MEAL (PLAN_ID, MEAL_PERIOD, DEL_FLAG, SORT_ORDER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='饮食方案明细';

CREATE TABLE HEALTH_PLAN_EXERCISE_ITEMS (
    ITEM_ID           VARCHAR(32)   PRIMARY KEY COMMENT '明细ID',
    PLAN_ID           VARCHAR(32)   NOT NULL COMMENT '方案ID',
    EXERCISE_TYPE     VARCHAR(50)   NOT NULL COMMENT '运动类型',
    DURATION_MINUTES  INT           DEFAULT NULL COMMENT '时长分钟',
    FREQUENCY         VARCHAR(50)   DEFAULT NULL COMMENT '频率',
    INTENSITY         TINYINT       DEFAULT 2 COMMENT '强度',
    CALORIES_BURNED   INT           DEFAULT NULL COMMENT '消耗热量',
    CAUTION           VARCHAR(500)  DEFAULT NULL COMMENT '注意事项',
    SORT_ORDER        TINYINT       DEFAULT 0 COMMENT '排序',
    DEL_FLAG          TINYINT       DEFAULT 0 COMMENT '逻辑删除',
    FOREIGN KEY (PLAN_ID) REFERENCES HEALTH_PLANS(PLAN_ID) ON DELETE CASCADE,
    INDEX IDX_PLAN (PLAN_ID, DEL_FLAG, SORT_ORDER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='运动方案明细';

CREATE TABLE HEALTH_PLAN_REST_ITEMS (
    ITEM_ID           VARCHAR(32)   PRIMARY KEY COMMENT '明细ID',
    PLAN_ID           VARCHAR(32)   NOT NULL COMMENT '方案ID',
    SCHEDULE_TYPE     TINYINT       NOT NULL COMMENT '类型',
    TIME_POINT        VARCHAR(100)  DEFAULT NULL COMMENT '时间点或监测时段（如 06:30、空腹、餐后2h）',
    SUGGESTION        TEXT          NOT NULL COMMENT '建议内容',
    SORT_ORDER        TINYINT       DEFAULT 0 COMMENT '排序',
    DEL_FLAG          TINYINT       DEFAULT 0 COMMENT '逻辑删除',
    FOREIGN KEY (PLAN_ID) REFERENCES HEALTH_PLANS(PLAN_ID) ON DELETE CASCADE,
    INDEX IDX_PLAN (PLAN_ID, DEL_FLAG, SORT_ORDER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='作息方案明细';

-- =============================================================================
-- DIABETES_ARTICLE
-- =============================================================================
CREATE DATABASE IF NOT EXISTS DIABETES_ARTICLE
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE DIABETES_ARTICLE;

CREATE TABLE ARTICLES (
    ARTICLE_ID            VARCHAR(32)   PRIMARY KEY COMMENT '资讯ID',
    TITLE                 VARCHAR(200)  NOT NULL COMMENT '标题',
    CONTENT               MEDIUMTEXT    NOT NULL COMMENT '正文Markdown',
    SUMMARY               VARCHAR(500)  DEFAULT NULL COMMENT '摘要',
    COVER_IMAGE_ID        VARCHAR(200)  DEFAULT NULL COMMENT '封面MinIO对象名（article桶），如 {articleId}.jpg',
    CATEGORY              TINYINT       NOT NULL COMMENT '分类：1基础 2饮食 3运动 4用药 5并发症',
    SOURCE_REF            VARCHAR(500)  DEFAULT NULL COMMENT '来源引用',
    AUTHOR_TYPE           TINYINT       DEFAULT 1 COMMENT '作者类型',
    AUTHOR_ID             VARCHAR(32)   DEFAULT NULL COMMENT '作者ID',
    STATUS                TINYINT       DEFAULT 1 COMMENT '状态：1草稿 2待审 3发布 4驳回',
    DIFY_DRAFT_RUN_ID     VARCHAR(64)   DEFAULT NULL COMMENT 'Dify编写工作流ID',
    DIFY_REVIEW_RUN_ID    VARCHAR(64)   DEFAULT NULL COMMENT 'Dify审核工作流ID',
    AI_REVIEW_STATUS      TINYINT       DEFAULT 0 COMMENT 'AI审核状态',
    AI_REVIEW_NOTE        TEXT          DEFAULT NULL COMMENT 'AI审核说明',
    AI_RAW_RESPONSE       JSON          DEFAULT NULL COMMENT 'AI原始输出',
    REJECT_REASON         VARCHAR(500)  DEFAULT NULL COMMENT '驳回原因',
    VIEW_COUNT            INT           DEFAULT 0 COMMENT '阅读量',
    FAVORITE_COUNT        INT           DEFAULT 0 COMMENT '收藏数',
    PUBLISHED_AT          DATETIME      DEFAULT NULL COMMENT '发布时间',
    REVIEWED_AT           DATETIME      DEFAULT NULL COMMENT '审核时间',
    DEL_FLAG              TINYINT       DEFAULT 0 COMMENT '逻辑删除',
    CREATED_AT            DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_AT            DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX IDX_STATUS_PUB (STATUS, DEL_FLAG, PUBLISHED_AT DESC),
    INDEX IDX_CATEGORY (CATEGORY, DEL_FLAG, STATUS),
    INDEX IDX_AI_REVIEW (AI_REVIEW_STATUS, STATUS, DEL_FLAG),
    FULLTEXT IDX_FT_TITLE_CONTENT (TITLE, CONTENT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='资讯主表';

CREATE TABLE ARTICLE_TAGS (
    TAG_ID            VARCHAR(32)   PRIMARY KEY COMMENT '标签ID',
    ARTICLE_ID        VARCHAR(32)   NOT NULL COMMENT '资讯ID',
    TAG_NAME          VARCHAR(50)   NOT NULL COMMENT '标签名',
    DEL_FLAG          TINYINT       DEFAULT 0 COMMENT '逻辑删除',
    CREATED_AT        DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES(ARTICLE_ID) ON DELETE CASCADE,
    INDEX IDX_ARTICLE (ARTICLE_ID, DEL_FLAG),
    INDEX IDX_TAG (TAG_NAME, DEL_FLAG)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='资讯标签表';

CREATE TABLE ARTICLE_TARGET_TAGS (
    TARGET_ID         VARCHAR(32)   PRIMARY KEY COMMENT '目标标签ID',
    ARTICLE_ID        VARCHAR(32)   NOT NULL COMMENT '资讯ID',
    TAG_KEY           VARCHAR(50)   NOT NULL COMMENT '标签键',
    TAG_VALUE         VARCHAR(50)   NOT NULL COMMENT '标签值',
    DEL_FLAG          TINYINT       DEFAULT 0 COMMENT '逻辑删除',
    CREATED_AT        DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES(ARTICLE_ID) ON DELETE CASCADE,
    INDEX IDX_ARTICLE (ARTICLE_ID, DEL_FLAG),
    INDEX IDX_TARGET (TAG_KEY, TAG_VALUE, DEL_FLAG)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='目标受众标签表';

CREATE TABLE ARTICLE_REVIEW_LOGS (
    LOG_ID            VARCHAR(32)   PRIMARY KEY COMMENT '审核记录ID',
    ARTICLE_ID        VARCHAR(32)   NOT NULL COMMENT '资讯ID',
    REVIEW_TYPE       TINYINT       NOT NULL COMMENT '审核类型',
    ACTION            TINYINT       NOT NULL COMMENT '动作',
    NOTE              TEXT          DEFAULT NULL COMMENT '审核意见',
    DIFY_RUN_ID       VARCHAR(64)   DEFAULT NULL COMMENT 'Dify工作流ID',
    OPERATOR_ID       VARCHAR(32)   DEFAULT NULL COMMENT '操作人ID',
    CREATED_AT        DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
    FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES(ARTICLE_ID) ON DELETE CASCADE,
    INDEX IDX_ARTICLE (ARTICLE_ID, CREATED_AT DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='资讯审核记录表';

CREATE TABLE ARTICLE_USER_READS (
    READ_ID           VARCHAR(32)   PRIMARY KEY COMMENT '阅读ID',
    USER_ID           VARCHAR(32)   NOT NULL COMMENT '用户ID',
    ARTICLE_ID        VARCHAR(32)   NOT NULL COMMENT '资讯ID',
    READ_DURATION     INT           DEFAULT NULL COMMENT '阅读时长秒',
    READ_SOURCE       VARCHAR(32)   DEFAULT 'detail' COMMENT '来源：recommend/search/category/detail',
    READ_AT           DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT '阅读时间',
    DEL_FLAG          TINYINT       DEFAULT 0 COMMENT '逻辑删除',
    FOREIGN KEY (USER_ID) REFERENCES DIABETES_USER.USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES(ARTICLE_ID) ON DELETE CASCADE,
    UNIQUE KEY UK_USER_ARTICLE (USER_ID, ARTICLE_ID),
    INDEX IDX_USER_READ (USER_ID, READ_AT DESC, DEL_FLAG),
    INDEX IDX_ARTICLE_READ (ARTICLE_ID, READ_AT DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户阅读记录表';

CREATE TABLE ARTICLE_EMBEDDINGS (
    ARTICLE_ID        VARCHAR(32)   PRIMARY KEY COMMENT '资讯ID',
    TEXT_FINGERPRINT  TEXT          DEFAULT NULL COMMENT '标题+摘要+标签文本（Milvus未启用时本地语义相似度）',
    MILVUS_VECTOR_ID  VARCHAR(64)   DEFAULT NULL COMMENT 'Milvus向量ID',
    UPDATED_AT        DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES(ARTICLE_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='资讯向量/语义指纹（Milvus同步预留）';

CREATE TABLE ARTICLE_RECOMMENDATIONS (
    REC_ID            VARCHAR(32)   PRIMARY KEY COMMENT '推荐ID',
    USER_ID           VARCHAR(32)   NOT NULL COMMENT '用户ID',
    ARTICLE_ID        VARCHAR(32)   NOT NULL COMMENT '资讯ID',
    REC_SCORE         DECIMAL(5,2)  DEFAULT NULL COMMENT '推荐分数',
    REC_REASON        VARCHAR(500)  DEFAULT NULL COMMENT '推荐理由',
    REC_BATCH_ID      VARCHAR(32)   DEFAULT NULL COMMENT '推荐批次ID',
    REC_PHASE         TINYINT       DEFAULT 1 COMMENT '推荐阶段：1规则 2协同 3语义 4Dify',
    DIFY_RUN_ID       VARCHAR(64)   DEFAULT NULL COMMENT 'Dify工作流ID',
    EXPIRED_AT        DATETIME      DEFAULT NULL COMMENT '过期时间',
    DEL_FLAG          TINYINT       DEFAULT 0 COMMENT '逻辑删除',
    CREATED_AT        DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT '推荐时间',
    FOREIGN KEY (USER_ID) REFERENCES DIABETES_USER.USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES(ARTICLE_ID) ON DELETE CASCADE,
    INDEX IDX_USER_REC (USER_ID, DEL_FLAG, REC_SCORE DESC, CREATED_AT DESC),
    INDEX IDX_BATCH (REC_BATCH_ID, USER_ID),
    INDEX IDX_USER_EXPIRE (USER_ID, EXPIRED_AT, DEL_FLAG)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='个性化推荐缓存表';

CREATE TABLE ARTICLE_FAVORITES (
    FAV_ID            VARCHAR(32)   PRIMARY KEY COMMENT '收藏ID',
    USER_ID           VARCHAR(32)   NOT NULL COMMENT '用户ID',
    ARTICLE_ID        VARCHAR(32)   NOT NULL COMMENT '资讯ID',
    IS_ACTIVE         TINYINT       DEFAULT 1 COMMENT '是否收藏中',
    DEL_FLAG          TINYINT       DEFAULT 0 COMMENT '逻辑删除',
    CREATED_AT        DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT '收藏时间',
    UPDATED_AT        DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY (USER_ID) REFERENCES DIABETES_USER.USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES(ARTICLE_ID) ON DELETE CASCADE,
    UNIQUE KEY UK_USER_ARTICLE (USER_ID, ARTICLE_ID),
    INDEX IDX_USER_ACTIVE (USER_ID, IS_ACTIVE, DEL_FLAG, CREATED_AT DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='资讯收藏表';

-- =============================================================================
-- DIABETES_AUDIT
-- =============================================================================
CREATE DATABASE IF NOT EXISTS DIABETES_AUDIT
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE DIABETES_AUDIT;

CREATE TABLE AUDIT_LOGS (
    LOG_ID            VARCHAR(32)   PRIMARY KEY COMMENT '日志ID',
    USER_ID           VARCHAR(32)   NOT NULL COMMENT '操作用户ID',
    ACTION            VARCHAR(100)  NOT NULL COMMENT '操作类型',
    RESOURCE          VARCHAR(200)  NOT NULL COMMENT '操作资源',
    DETAIL            JSON          DEFAULT NULL COMMENT '操作详情',
    IP_ADDRESS        VARCHAR(50)   DEFAULT NULL COMMENT '操作IP',
    USER_AGENT        VARCHAR(500)  DEFAULT NULL COMMENT 'User-Agent',
    RESULT            TINYINT       NOT NULL COMMENT '结果：1成功 0失败',
    CREATED_AT        DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
    INDEX IDX_USER_TIME (USER_ID, CREATED_AT DESC),
    INDEX IDX_ACTION (ACTION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='审计日志表';

SET FOREIGN_KEY_CHECKS = 1;
